---
- name: ubuntu vm configuration
  hosts: ubuntu
  become: true
  vars:
    cowsay_package_name: cowsay

  tasks: 
  - name: Install cowsay
    tags: packages
    ansible.builtin.package:
      name: "{{ cowsay_package_name }}"
      state: present
      update_cache: true
  - name: add newuser
    tags: users
    ansible.builtin.user:
      name: newuser
